title: Adam Vitaris
description: Cybersecurity projects
remote_theme: jekyll/minima@v2.5.1
header_pages:
  -about.md
  -projects.md

plugins:
  - jekyll-remote-theme

# Opcionális:
minima:
  skin: auto
